# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWN9vuz3MyS2BgeHOJZbmn4Bcg_9G70w
"""

def mostrar_menu():

  print("CONVERSOR DE TEMPERATURAS")

  print("[1] °C -> °F")

  print("[2] °F -> °C")

  print("[3] Salir")

def pedir_temperatura():

  temp = float(input("Ingrese la temperatura: "))

  return temp


def celsius_a_fahrenheit(c):

  return (c * 9 / 5) + 32

def fahrenheit_a_celsius(f):

  return (f - 32) * 5 / 9


def mostrar_resultado(orig, conv, ud):

  print(f"{orig}° {ud[0]} = {conv:.2f}° {ud[1]}")



while True:

  mostrar_menu()

  opcion = int(input("Seleccione una opción: "))

  if opcion == 1:

    temperatura = pedir_temperatura()

    resultado = celsius_a_fahrenheit(temperatura)

    mostrar_resultado(temperatura, resultado, "CF")

  elif opcion == 2:

    temperatura = pedir_temperatura()

    resultado = fahrenheit_a_celsius(temperatura)

    mostrar_resultado(temperatura, resultado, "FC")

  elif opcion == 3:

    print("Programa finalizado.")

    break

  else:

    print("Opción inválida.")